version: '3.9'

services:
  matching:
    build:
      context: services/matching
      dockerfile: Dockerfile
    image: matching
    command: /usr/src/app/node_modules/.bin/nodemon app.js
    ports:
      - "4000:4000"
    depends_on:
      - api-gateway
    networks:
      - app-network
  chat:
    build:
      context: services/chat
      dockerfile: Dockerfile
    image: chat
    ports:
      - "5000:5000"
    depends_on:
      - api-gateway
    networks:
      - app-network
  editor:
    build:
      context: services/editor
      dockerfile: Dockerfile
    image: editor
    ports:
      - "6001:6001"
    depends_on:
      - api-gateway
    networks:
      - app-network
  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    image: matching
    command: /usr/src/app/node_modules/.bin/nodemon app.js
    ports:
      - "8080:8080"
    networks:
      - app-network
  client:
    build:
      context: frontend/app
      dockerfile: Dockerfile
    image: peerprep-client
    stdin_open: true
    command: npm start
    depends_on:
      - api-gateway
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
