http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  chat:
    host: localhost
    paths: ['/chat', '/chat/*']
  editor:
    host: localhost
    paths: ['/editor', '/editor/*']
  matching:
    host: localhost
    paths: ['/matching', '/matching/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  chatService:
    url: 'http://localhost:5000'
  editorService:
    url: 'http://localhost:6001'
  matchingService:
    url: 'http://localhost:4000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - auth
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - auth:
          - action:
              baseUrl: 'https://example.com'
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  chatPipeline:
    apiEndpoints:
      - chat
    policies:
      - auth:
          - action:
              baseUrl: 'https://example.com'
      - proxy:
          - action:
              serviceEndpoint: chatService
              changeOrigin: true
  editorPipeline:
    apiEndpoints:
      - editor
    policies:
      - auth:
          - action:
              baseUrl: 'https://example.com'
      - proxy:
          - action:
              serviceEndpoint: editorService
              changeOrigin: true
  matchingPipeline:
    apiEndpoints:
      - matching
    policies:
      - auth:
          - action:
              baseUrl: 'https://example.com'
      - proxy:
          - action:
              serviceEndpoint: matchingService
              changeOrigin: true
