apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: pp-frontend-config
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: pp-backend-config
spec:
  timeoutSec: 720000
  securityPolicy:
    name: "peerprep-security-policy"
#  customRequestHeaders:
#    headers:
#    - "Strict-Transport-Security: max-age=31536000; includeSubDomains"
#    - "Content-Security-Policy:default-src 'none';"
#    - "X-Content-Type-Options: nosniff"
#    - "X-Frame-Options: SAMEORIGIN"
#    - "Referrer-Policy: strict-origin-when-cross-origin"
