apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-peerprep
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.org/websocket-services : "peerprep-chat"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/websocket-services: "socket-service"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: $http_origin";
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: peerprep-client
                port:
                  number: 3000
    - http:
        paths:
          - pathType: Prefix
            path: /matching
            backend:
              service:
                name: peerprep-matching
                port:
                  number: 4000
    - http:
        paths:
          - pathType: Prefix
            path: /chat
            backend:
              service:
                name: peerprep-chat
                port:
                  number: 5000
    - http:
        paths:
          - pathType: Prefix
            path: /editor
            backend:
              service:
                name: peerprep-editor
                port:
                  number: 6001
